export const blogs = [
  {
    id: 1,
    slug: "investment-strategies-2025",
    title: "Top 5 Investment Strategies for 2025",
    excerpt: "Discover the most effective investment strategies that financial experts recommend for growing your wealth in 2025.",
    category: "Investment",
    date: "March 15, 2025",
    readTime: "5 min read",
    author: "Rahul Sharma",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    tableOfContents: [
      { id: "intro",      label: "Introduction" },
      { id: "strategy1",  label: "Diversified Portfolio" },
      { id: "strategy2",  label: "SIP in Mutual Funds" },
      { id: "strategy3",  label: "Index Fund Investing" },
      { id: "strategy4",  label: "Real Estate Investment" },
      { id: "strategy5",  label: "Gold & Commodities" },
      { id: "conclusion", label: "Conclusion" },
    ],
    content: [
      { id: "intro",      heading: "Introduction",           body: "Investing wisely is the cornerstone of building long-term wealth. As we move into 2025, the financial landscape continues to evolve with new opportunities and challenges. Whether you are a first-time investor or an experienced one, having a clear strategy is essential to achieving your financial goals." },
      { id: "strategy1",  heading: "Diversified Portfolio",  body: "Diversification remains the most fundamental principle of investing. By spreading your investments across different asset classes — equities, bonds, real estate, and commodities — you reduce the risk of any single investment dragging down your entire portfolio." },
      { id: "strategy2",  heading: "SIP in Mutual Funds",    body: "Systematic Investment Plans (SIPs) allow you to invest a fixed amount every month in mutual funds. This strategy leverages rupee cost averaging, meaning you buy more units when prices are low and fewer when prices are high. Over a long period, this approach smooths out market volatility and builds significant wealth." },
      { id: "strategy3",  heading: "Index Fund Investing",   body: "Index funds track a market index like Nifty 50 or Sensex and offer broad market exposure at very low costs. Studies consistently show that most actively managed funds fail to beat the index over long periods. For investors who want steady, market-matching returns without the complexity of stock picking, index funds are an excellent choice." },
      { id: "strategy4",  heading: "Real Estate Investment", body: "Real estate continues to be a popular investment in India. Whether through direct property purchase or Real Estate Investment Trusts (REITs), property offers the dual benefit of capital appreciation and rental income. REITs in particular have made real estate investment accessible to retail investors with smaller capital requirements." },
      { id: "strategy5",  heading: "Gold & Commodities",     body: "Gold has historically served as a safe haven during economic uncertainty. In 2025, allocating 10-15% of your portfolio to gold — through Sovereign Gold Bonds, Gold ETFs, or digital gold — provides a valuable hedge against currency depreciation and market volatility." },
      { id: "conclusion", heading: "Conclusion",             body: "The best investment strategy is one that aligns with your financial goals, risk tolerance, and time horizon. Start early, stay consistent, and review your portfolio periodically. FinPlexus can help you build a personalised investment plan tailored to your unique needs." },
    ],
  },
  {
    id: 2,
    slug: "emergency-fund-guide",
    title: "How to Build an Emergency Fund",
    excerpt: "Learn why an emergency fund is the foundation of financial security and how to build one that works for you.",
    category: "Personal Finance",
    date: "March 10, 2025",
    readTime: "4 min read",
    author: "Priya Mehta",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&q=80",
    tableOfContents: [
      { id: "what",  label: "What is an Emergency Fund?" },
      { id: "why",   label: "Why Do You Need One?" },
      { id: "how",   label: "How Much Should You Save?" },
      { id: "where", label: "Where to Keep It?" },
      { id: "tips",  label: "Tips to Build It Faster" },
    ],
    content: [
      { id: "what",  heading: "What is an Emergency Fund?", body: "An emergency fund is a dedicated pool of money set aside to cover unexpected expenses — such as job loss, medical bills, car repairs, or urgent home maintenance. It acts as a financial buffer that keeps you from going into debt when life throws an unexpected curveball." },
      { id: "why",   heading: "Why Do You Need One?",        body: "Without an emergency fund, a sudden financial shock can derail your long-term financial plans. You may be forced to liquidate investments at a loss, take high-interest loans, or use credit cards that accumulate debt. An emergency fund gives you peace of mind and financial stability." },
      { id: "how",   heading: "How Much Should You Save?",   body: "Financial experts generally recommend saving 3 to 6 months of your monthly living expenses. If you have dependents, irregular income, or work in a volatile industry, aim for 6 to 12 months. Calculate your essential monthly expenses and multiply by your target months." },
      { id: "where", heading: "Where to Keep It?",           body: "Your emergency fund should be kept in a highly liquid, low-risk account. A high-yield savings account or liquid mutual fund is ideal. Avoid investing it in equities or long-term instruments. The goal is instant accessibility, not high returns." },
      { id: "tips",  heading: "Tips to Build It Faster",     body: "Start small — even saving ₹500 a month adds up. Automate transfers to your emergency fund on salary day so you save before you spend. Use windfalls like bonuses, tax refunds, or gifts to boost it. Cut discretionary spending temporarily and redirect that money." },
    ],
  },
  {
    id: 3,
    slug: "tax-planning-salaried",
    title: "Tax Planning Tips for Salaried Employees",
    excerpt: "Smart tax planning can save you thousands. Here are the best tax-saving options available for salaried individuals.",
    category: "Tax",
    date: "Feb 28, 2025",
    readTime: "7 min read",
    author: "Amit Verma",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    tableOfContents: [
      { id: "80c",    label: "Section 80C Deductions" },
      { id: "80d",    label: "Section 80D — Health Insurance" },
      { id: "hra",    label: "HRA Exemption" },
      { id: "nps",    label: "NPS Benefits" },
      { id: "regime", label: "Old vs New Tax Regime" },
    ],
    content: [
      { id: "80c",    heading: "Section 80C Deductions",        body: "Section 80C allows deductions up to ₹1.5 lakh per year through EPF, PPF, ELSS mutual funds, NSC, life insurance premiums, and home loan principal repayment. ELSS funds are particularly popular as they offer the shortest lock-in period of 3 years among 80C options." },
      { id: "80d",    heading: "Section 80D — Health Insurance", body: "Premiums paid for health insurance are deductible under Section 80D. You can claim up to ₹25,000 for yourself and your family, and an additional ₹25,000–₹50,000 for parents depending on their age. This is one of the most valuable and often overlooked tax-saving instruments." },
      { id: "hra",    heading: "HRA Exemption",                  body: "HRA exemption is the minimum of: actual HRA received, 50% of basic salary (40% for non-metro cities), or actual rent paid minus 10% of basic salary. Keep rent receipts and your landlord's PAN if annual rent exceeds ₹1 lakh." },
      { id: "nps",    heading: "NPS Benefits",                   body: "The National Pension System offers an additional deduction of ₹50,000 under Section 80CCD(1B), over and above the ₹1.5 lakh 80C limit. This makes NPS one of the most tax-efficient instruments for salaried employees." },
      { id: "regime", heading: "Old vs New Tax Regime",          body: "From FY 2023-24, the new tax regime is the default but you can opt for the old regime. The old regime allows deductions and exemptions while the new regime offers lower rates without most deductions. If your deductions exceed ₹3.75 lakh, the old regime may save you more tax." },
    ],
  },
  {
    id: 4,
    slug: "mutual-funds-vs-stocks",
    title: "Mutual Funds vs Direct Stocks: Which is Better?",
    excerpt: "Not sure whether to invest in mutual funds or pick stocks yourself? We break down the pros and cons of each.",
    category: "Investment",
    date: "Feb 20, 2025",
    readTime: "5 min read",
    author: "Rahul Sharma",
    image: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&q=80",
    tableOfContents: [
      { id: "overview",    label: "Overview" },
      { id: "mutualfunds", label: "Mutual Funds Explained" },
      { id: "stocks",      label: "Direct Stock Investing" },
      { id: "comparison",  label: "Key Differences" },
      { id: "who",         label: "Who Should Choose What?" },
    ],
    content: [
      { id: "overview",    heading: "Overview",                body: "One of the most common dilemmas for investors is whether to invest in mutual funds or directly in stocks. Both have their merits, and the right choice depends on your knowledge, time availability, risk appetite, and financial goals." },
      { id: "mutualfunds", heading: "Mutual Funds Explained", body: "Mutual funds pool money from multiple investors to invest in a diversified portfolio managed by professional fund managers. They offer diversification, professional management, and systematic investment options starting at just ₹500 per month." },
      { id: "stocks",      heading: "Direct Stock Investing",  body: "Direct stock investing means buying shares of individual companies on the stock exchange. It offers higher potential returns but requires significant research, time, and knowledge of company financials, industry trends, and macroeconomic factors." },
      { id: "comparison",  heading: "Key Differences",        body: "Mutual funds offer instant diversification and professional management at low cost. Direct stocks give you full control and can significantly outperform funds if you pick the right companies. Transaction costs are higher for small investors in direct stocks." },
      { id: "who",         heading: "Who Should Choose What?", body: "Beginners and those with limited time should start with mutual funds. Experienced investors with time to research can consider direct stocks. Many successful investors do both — using mutual funds as the core of their portfolio and selecting a few high-conviction stocks for additional returns." },
    ],
  },
  {
    id: 5,
    slug: "compound-interest-power",
    title: "The Power of Compound Interest",
    excerpt: "Einstein called it the eighth wonder of the world. Understand how compound interest can transform your savings.",
    category: "Personal Finance",
    date: "Feb 15, 2025",
    readTime: "4 min read",
    author: "Priya Mehta",
    image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&q=80",
    tableOfContents: [
      { id: "what",     label: "What is Compound Interest?" },
      { id: "how",      label: "How it Works" },
      { id: "examples", label: "Real-World Examples" },
      { id: "tips",     label: "How to Maximise It" },
    ],
    content: [
      { id: "what",     heading: "What is Compound Interest?", body: "Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods. Unlike simple interest, it grows exponentially over time, making it a powerful tool for wealth creation." },
      { id: "how",      heading: "How it Works",               body: "The formula is A = P(1 + r/n)^(nt). The key insight is that more frequent compounding and longer time periods lead to dramatically higher returns. This is why starting to invest early, even small amounts, creates significantly more wealth than starting later with larger amounts." },
      { id: "examples", heading: "Real-World Examples",        body: "If you invest ₹1,00,000 at 12% annual return for 20 years, you end up with approximately ₹9,64,629 — nearly 10x your investment. The same investment for 30 years gives ₹29,95,992 — nearly 30x. This exponential growth in the later years is why starting early matters so much." },
      { id: "tips",     heading: "How to Maximise It",         body: "Start as early as possible — even 5 years earlier can double your final corpus. Reinvest all dividends and returns rather than withdrawing them. Choose instruments with frequent compounding. Avoid breaking investments prematurely as you lose the compounding effect on accumulated gains." },
    ],
  },
  {
    id: 6,
    slug: "understanding-market-volatility",
    title: "Understanding Market Volatility",
    excerpt: "Market swings can be scary. Here's how to stay calm and make smart decisions during volatile market conditions.",
    category: "Markets",
    date: "March 5, 2025",
    readTime: "6 min read",
    author: "Amit Verma",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    tableOfContents: [
      { id: "what",   label: "What is Market Volatility?" },
      { id: "causes", label: "What Causes Volatility?" },
      { id: "impact", label: "Impact on Your Portfolio" },
      { id: "dos",    label: "What to Do During Volatility" },
      { id: "donts",  label: "Common Mistakes to Avoid" },
    ],
    content: [
      { id: "what",   heading: "What is Market Volatility?",      body: "Market volatility refers to the rate at which the price of securities increases or decreases for a given set of returns. High volatility means prices can change dramatically in a short time in either direction. Volatility is measured by the VIX index — sometimes called the 'fear index'." },
      { id: "causes", heading: "What Causes Volatility?",         body: "Market volatility is caused by economic data releases, geopolitical events, changes in interest rates, corporate earnings announcements, and global market trends. Uncertainty is the primary driver — when investors are unsure about future economic conditions, they react quickly to new information." },
      { id: "impact", heading: "Impact on Your Portfolio",        body: "Short-term volatility can be unsettling as portfolio values fluctuate. However, for long-term investors, volatility is normal and expected. Historically, markets have always recovered from downturns and reached new highs. The real risk is making emotional decisions during volatile periods." },
      { id: "dos",    heading: "What to Do During Volatility",    body: "Continue your SIPs — market downturns are actually opportunities to buy more units at lower prices. Review your asset allocation and rebalance if needed. Stay informed but avoid obsessively checking your portfolio daily. Consider increasing equity exposure if your time horizon allows." },
      { id: "donts",  heading: "Common Mistakes to Avoid",        body: "Don't panic sell during market downturns — you turn paper losses into real losses. Don't try to time the market — even professional investors fail at this consistently. Don't stop your SIPs — this is exactly when they work best. Don't make investment decisions based on news headlines." },
    ],
  },
];

export const categories = ["All", "Investment", "Personal Finance", "Tax", "Markets"];
